site_name: Kira Night Rain's
site_url: https://NightRain5212.github.io/docs/

theme:
  name: material
  font:
    text: roboto
    code: roboto mono
  language: zh
  icon:
    logo: material/star-four-points

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.prune 
    - navigation.top
    - navigation.path
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

  palette:
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: pink
      accent: pink

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
    
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - minify

extra:
  analytics:
    provider: google
    property: G-3LVJPB5XL9


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - pymdownx.keys
  - toc:
      permalink: true

  - pymdownx.betterem
  - pymdownx.arithmatex:
      # generic: true 选项让插件能够识别标准的 LaTeX 定界符，
      # 例如 $$...$$ 用于块级公式, $...$ 用于行内公式。
      generic: true
  

# 在 extra_javascript 部分加载 MathJax
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js